### ISSUE TITLE
lasclipPolygon

### ISSUE THREAD

**Issue by ingridsnoan** [JamesDMSpeed/LidarMoose#2]
Struggeling to make the xpoly and ypoly that goes into the lasclipPolygon function. 
lasclipPolygon(x, xpoly, ypoly, ofile = "", inside = TRUE, ...)
Do I get it from the bratsberg_b_poly or from  the plotcoords?

Ingrid

**Comment by JamesDMSpeed** [comment]
Use the function lasclip(mylasfile, mypolygon)
See lines 25-26 in the clipping script which makes an object called bbx (this is the bratsberg browsed plot).
