### ISSUE TITLE
Problem in clipping script

### ISSUE THREAD

**Issue by ingridsnoan** [JamesDMSpeed/LidarMoose#3]
Error in line 113 in the clipping script.
Run: nsb_verdal_ub_poly<-Polygon(as.matrix(plotcoords[plotcoords$Name=='1Nsub',4:5][nsb_verdal_ub_order,]))
Error: Error in .local(obj, ...) : 
  cannot derive coordinates from non-numeric matrix

**Comment by anders-kolstad** [comment]
I'm having a quick look now...

**Comment by ingridsnoan** [comment]
Thanks :)

**Comment by anders-kolstad** [comment]
Har du Nsb_Verdal.las et sted? Kan ikke finne noen feil, så må prøve med dataene...

**Comment by ingridsnoan** [comment]
Kun lokalt på PC'en, de filene var for store for github. Er du på kontoret kan jeg komme nedom evt.

**Comment by anders-kolstad** [comment]
Ja gjør det :)

**Comment by anders-kolstad** [comment]
found space before plot name
