### ISSUE TITLE
halvard_pramhus 

### ISSUE THREAD

**Issue by ingridsnoan** [JamesDMSpeed/LidarMoose#4]
I'm trying to save the new version of halvard pramhus ub after we removed the outliers. However, I just get an error message when I try to run line 826 in the clipping script (this is the line which saves the clipped las file).

Error in if (max(data$Z) > header$`Max Z` | min(data$Z) < header$`Min Z`) warning("Invalid file: some points are outside the elevation range defined by the header",  : 
  missing value where TRUE/FALSE needed

Can you help me? :)

**Comment by JamesDMSpeed** [comment]
So it seems you cannot write a las file with NA values in Z (at least not without modifying the headers). I suggest that you skip the step setting the unusually high Z values to NA from the clipping step. Instead deal with them when making the canopy and terrain models
